// Smart Media presets — premium backgrounds + font styles for lyrics slides

export const FONT_OPTIONS = [
  { id: 'cormorant',   label: 'Cormorant',   family: "'Cormorant Garamond', Georgia, serif",     weight: 400, description: 'Elegant serif' },
  { id: 'montserrat',  label: 'Montserrat',  family: "'Montserrat', 'Inter', sans-serif",          weight: 700, description: 'Bold & modern' },
  { id: 'opensans',    label: 'Open Sans',   family: "'Open Sans', 'Inter', sans-serif",            weight: 700, description: 'Clean & readable' },
  { id: 'georgia',     label: 'Georgia',     family: "Georgia, 'Times New Roman', serif",           weight: 700, description: 'Classic bold' },
  { id: 'impact',      label: 'Impact',      family: "Impact, 'Arial Black', sans-serif",           weight: 900, description: 'Maximum impact' },
]

export const SMART_MEDIA_PRESETS = [
  {
    id: 'none',
    label: 'None',
    type: 'color',
    preview: '#050813',
    bgColor: '#050813',
    bgGradient: null,
    bgImageUrl: null,
    textColor: '#ffffff',
    overlayOpacity: 0,
    fontId: 'cormorant',
  },

  // ── Church image backgrounds ──────────────────────────────────────────────
  {
    id: 'three-crosses',
    label: 'Three Crosses',
    type: 'image',
    preview: './backgrounds/bg-three-crosses.jpg',
    bgColor: '#000',
    bgGradient: null,
    bgImageUrl: './backgrounds/bg-three-crosses.jpg',
    textColor: '#ffffff',
    overlayOpacity: 0.70,
    fontId: 'montserrat',
  },
  {
    id: 'light-waves',
    label: 'Light Waves',
    type: 'image',
    preview: './backgrounds/bg-light-waves.jpg',
    bgColor: '#000',
    bgGradient: null,
    bgImageUrl: './backgrounds/bg-light-waves.jpg',
    textColor: '#ffffff',
    overlayOpacity: 0.45,
    fontId: 'montserrat',
  },
  {
    id: 'heavenly-sky',
    label: 'Heavenly Sky',
    type: 'image',
    preview: './backgrounds/bg-heavenly-sky.jpg',
    bgColor: '#000',
    bgGradient: null,
    bgImageUrl: './backgrounds/bg-heavenly-sky.jpg',
    textColor: '#ffffff',
    overlayOpacity: 0.72,
    fontId: 'montserrat',
  },
  {
    id: 'divine-light',
    label: 'Divine Light',
    type: 'image',
    preview: './backgrounds/bg-divine-light.jpg',
    bgColor: '#000',
    bgGradient: null,
    bgImageUrl: './backgrounds/bg-divine-light.jpg',
    textColor: '#ffffff',
    overlayOpacity: 0.60,
    fontId: 'montserrat',
  },
  {
    id: 'star-cluster',
    label: 'Star Cluster',
    type: 'image',
    preview: './backgrounds/bg-star-cluster.jpg',
    bgColor: '#000',
    bgGradient: null,
    bgImageUrl: './backgrounds/bg-star-cluster.jpg',
    textColor: '#ffffff',
    overlayOpacity: 0.40,
    fontId: 'montserrat',
  },

  // ── New church image backgrounds ─────────────────────────────────────────
  {
    id: 'empty-tomb',
    label: 'Empty Tomb',
    type: 'image',
    preview: './backgrounds/bg-empty-tomb.jpg',
    bgColor: '#000', bgGradient: null,
    bgImageUrl: './backgrounds/bg-empty-tomb.jpg',
    textColor: '#ffffff', overlayOpacity: 0.72, fontId: 'montserrat',
  },
  {
    id: 'communion',
    label: 'Communion',
    type: 'image',
    preview: './backgrounds/bg-communion.jpg',
    bgColor: '#000', bgGradient: null,
    bgImageUrl: './backgrounds/bg-communion.jpg',
    textColor: '#fff8e7', overlayOpacity: 0.68, fontId: 'montserrat',
  },
  {
    id: 'palm-leaves',
    label: 'Palm Leaves',
    type: 'image',
    preview: './backgrounds/bg-palm-leaves.jpg',
    bgColor: '#000', bgGradient: null,
    bgImageUrl: './backgrounds/bg-palm-leaves.jpg',
    textColor: '#ffffff', overlayOpacity: 0.25, fontId: 'montserrat',
  },
  {
    id: 'night-sky',
    label: 'Night Sky',
    type: 'image',
    preview: './backgrounds/bg-night-sky.jpg',
    bgColor: '#000', bgGradient: null,
    bgImageUrl: './backgrounds/bg-night-sky.jpg',
    textColor: '#ffffff', overlayOpacity: 0.40, fontId: 'montserrat',
  },
  {
    id: 'crosses-sunset',
    label: 'Crosses Sunset',
    type: 'image',
    preview: './backgrounds/bg-crosses-sunset.jpg',
    bgColor: '#000', bgGradient: null,
    bgImageUrl: './backgrounds/bg-crosses-sunset.jpg',
    textColor: '#ffffff', overlayOpacity: 0.78, fontId: 'montserrat',
  },
  {
    id: 'neon-burst',
    label: 'Neon Burst',
    type: 'image',
    preview: './backgrounds/bg-neon-burst.jpg',
    bgColor: '#000', bgGradient: null,
    bgImageUrl: './backgrounds/bg-neon-burst.jpg',
    textColor: '#ffffff', overlayOpacity: 0.20, fontId: 'montserrat',
  },
  {
    id: 'crystal-cross',
    label: 'Crystal Cross',
    type: 'image',
    preview: './backgrounds/bg-crystal-cross.jpg',
    bgColor: '#000', bgGradient: null,
    bgImageUrl: './backgrounds/bg-crystal-cross.jpg',
    textColor: '#ffffff', overlayOpacity: 0.30, fontId: 'montserrat',
  },
  {
    id: 'blue-nebula',
    label: 'Blue Nebula',
    type: 'image',
    preview: './backgrounds/bg-blue-nebula.jpg',
    bgColor: '#000', bgGradient: null,
    bgImageUrl: './backgrounds/bg-blue-nebula.jpg',
    textColor: '#ffffff', overlayOpacity: 0.35, fontId: 'montserrat',
  },

  // ── Gradient presets ──────────────────────────────────────────────────────
  {
    id: 'deep-navy',
    label: 'Deep Navy',
    type: 'gradient',
    preview: 'linear-gradient(135deg, #0a0e1a, #1a2a4a)',
    bgColor: '#0a0e1a',
    bgGradient: 'linear-gradient(160deg, #0a0e1a 0%, #1a2a4a 100%)',
    bgImageUrl: null,
    textColor: '#ffffff',
    overlayOpacity: 0,
    fontId: 'montserrat',
  },
  {
    id: 'midnight-blue',
    label: 'Midnight Blue',
    type: 'gradient',
    preview: 'linear-gradient(135deg, #000428, #004e92)',
    bgColor: '#000428',
    bgGradient: 'linear-gradient(160deg, #000428 0%, #004e92 100%)',
    bgImageUrl: null,
    textColor: '#ffffff',
    overlayOpacity: 0,
    fontId: 'montserrat',
  },
  {
    id: 'royal-purple',
    label: 'Royal Purple',
    type: 'gradient',
    preview: 'linear-gradient(135deg, #0d0221, #3a1f6e)',
    bgColor: '#0d0221',
    bgGradient: 'linear-gradient(160deg, #0d0221 0%, #3a1f6e 100%)',
    bgImageUrl: null,
    textColor: '#ffffff',
    overlayOpacity: 0,
    fontId: 'montserrat',
  },
  {
    id: 'deep-teal',
    label: 'Deep Teal',
    type: 'gradient',
    preview: 'linear-gradient(135deg, #010e05, #0a3d2e)',
    bgColor: '#010e05',
    bgGradient: 'linear-gradient(160deg, #010e05 0%, #0a3d2e 100%)',
    bgImageUrl: null,
    textColor: '#ffffff',
    overlayOpacity: 0,
    fontId: 'montserrat',
  },
  {
    id: 'gold-black',
    label: 'Gold on Black',
    type: 'gradient',
    preview: 'linear-gradient(135deg, #0a0800, #1a1400)',
    bgColor: '#0a0800',
    bgGradient: 'linear-gradient(160deg, #0a0800 0%, #1a1400 100%)',
    bgImageUrl: null,
    textColor: '#ffd700',
    overlayOpacity: 0,
    fontId: 'montserrat',
  },
  {
    id: 'pure-black',
    label: 'Pure Black',
    type: 'color',
    preview: '#000000',
    bgColor: '#000000',
    bgGradient: null,
    bgImageUrl: null,
    textColor: '#ffffff',
    overlayOpacity: 0,
    fontId: 'montserrat',
  },
]

export function applySmartMedia(preset, customImageUrl = null, overlayOpacity = 0.60) {
  if (customImageUrl) {
    return {
      bgColor: '#000000',
      bgGradient: null,
      bgImageUrl: customImageUrl,
      bgOverlayOpacity: overlayOpacity,
      textColor: '#ffffff',
      smartMediaId: 'custom-image',
      fontId: 'montserrat',
    }
  }
  return {
    bgColor: preset.bgColor,
    bgGradient: preset.bgGradient || null,
    bgImageUrl: preset.bgImageUrl || null,
    bgOverlayOpacity: preset.overlayOpacity,
    textColor: preset.textColor,
    smartMediaId: preset.id,
    fontId: preset.fontId || 'montserrat',
  }
}
